In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('vgsales.csv')
df

In [ ]:
plat_group = df.groupby('Platform')
plat_group

In [ ]:
plat_group.get_group('PS4')

In [ ]:
plat_group['Year'].value_counts().loc[['PS4','PS2']]

In [ ]:
plat_group['Genre'].value_counts()

In [ ]:
plat_group['Global_Sales'].describe().sort_values(by='max', ascending=False).reset_index()

In [3]:
df2 = pd.read_csv('stackoverflow/survey_results_public.csv')
pd.set_option('max_columns', 84)
df2.head(3)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN

In [4]:
df3 = df2[['ResponseId', 'LanguageHaveWorkedWith']]
df3

       ResponseId                         LanguageHaveWorkedWith
0               1  C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift
1               2                              JavaScript;Python
2               3                       Assembly;C;Python;R;Rust
3               4                          JavaScript;TypeScript
4               5                 Bash/Shell;HTML/CSS;Python;SQL
...           ...                                            ...
83434       83435                             Clojure;Kotlin;SQL
83435       83436                                            NaN
83436       83437                             Groovy;Java;Python
83437       83438           Bash/Shell;JavaScript;Node.js;Python
83438       83439         Delphi;Elixir;HTML/CSS;Java;JavaScript

[83439 rows x 2 columns]

In [6]:
df4 = pd.read_csv('LanguageHaveWorkedWith.csv', index_col=0)
df4

       ResponseId                         LanguageHaveWorkedWith
0               1  C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift
1               2                              JavaScript;Python
2               3                       Assembly;C;Python;R;Rust
3               4                          JavaScript;TypeScript
4               5                 Bash/Shell;HTML/CSS;Python;SQL
...           ...                                            ...
83434       83435                             Clojure;Kotlin;SQL
83435       83436                                            NaN
83436       83437                             Groovy;Java;Python
83437       83438           Bash/Shell;JavaScript;Node.js;Python
83438       83439         Delphi;Elixir;HTML/CSS;Java;JavaScript

[83439 rows x 2 columns]